import { Inter } from "next/font/google";
import Head from "next/head";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { MantineProvider, ColorSchemeScript } from "@mantine/core";
import { UserSessionContextProvider } from "@/context/UserSessionContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "CarLEXotics",
  description: "Generated by Car Exotics",
  icons: {
    icon: [
      {
        // Use the baseUrl to construct the absolute URL for the favicon image
        url: `/favicon.ico`,
        href: `/favicon.ico`, // You can update href as well if necessary
      },
    ],
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        {/* Favicon after description */}
        {/* <link rel="icon" href="/favicon.ico" /> */}
        {metadata.icons.icon.map((icon, index) => (
          <link key={index} rel="icon" href={icon.href} />
        ))}
      </Head>
      <body className={inter.className}>
        <MantineProvider>
          <UserSessionContextProvider>
            <Header />
            {children}
            <Footer />
          </UserSessionContextProvider>
        </MantineProvider>
      </body>
    </html>
  );
}
